<?php

namespace Jobz\CoreBundle\Repository;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLatest($num)
    {
        $em = $this->getEntityManager();

        $qb = $em->getRepository('CoreBundle:Job')
            ->createQueryBuilder('j')
            ->setMaxResults($num);

        return $qb->getQuery()->getResult();
    }

    public function findByKeyword($keyword)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            "SELECT j
			 FROM Jobz\CoreBundle\Entity\Job j
			 WHERE j.location LIKE :keyword
			 OR j.company LIKE :keyword
			 OR j.position LIKE :keyword"
        );

        $query->setParameter('keyword', '%'.$keyword.'%');
        return $query->getResult();

    }
}

